name: CI
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet pack Deepgram.sln --configuration Release --no-restore --output dist
      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: 'dist'
      - name: Publish to Nuget
        uses: dansiegel/publish-nuget@v1.01
        with:
          apiKey: ${{ secrets.NUGET_API_KEY }}